spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # jwk-set-uri: ${mockwebserver.url}/.well-known/jwks.json
          jwk-set-uri: http://localhost:9000/realms/master/protocol/openid-connect/certs

sample:
  jwe-key-value: classpath:simple.priv
